services:
  nostr-relay:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nostr-relay
    restart: always
    volumes:
      - ./data:/usr/src/app/db
      - ./config.toml:/usr/src/app/config.toml:ro
    ports:
      # Only expose to localhost - Caddy will proxy to this
      - "127.0.0.1:8080:8080"
    environment:
      - TZ=UTC
      - RUST_LOG=warn,nostr_rs_relay=info
    networks:
      - nostr-network

networks:
  nostr-network:
    driver: bridge
